apiVersion: apps/v1
kind: Deployment
metadata:
  name: j26-auth
spec:
  selector:
    matchLabels:
      app: j26-auth
  template:
    metadata:
      labels:
        app: j26-auth
    spec:
      containers:
        - name: app
          image: ghcr.io/scouterna/j26-auth:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: j26-auth-config
            - secretRef:
                name: keycloak-secrets
